

#ifndef BUFSIZ
#define BUFSIZ			(1<<16)
#endif

#define RULE_DEFAULT		RULE_ACCEPT

#define MAXRULES		(1<<8)
#define MAXARGUMENTS		(1<<8)

#define FANOTIFY_FLAGS		(FAN_CLOEXEC|FAN_UNLIMITED_QUEUE|FAN_UNLIMITED_MARKS)
#define FANOTIFY_EVFLAGS	(O_LARGEFILE|O_RDONLY|O_CLOEXEC)

#define FANOTIFY_MARKMASK	(FAN_CLOSE_WRITE)

