Document: clsync
Title: Debian clsync Manual
Author: <insert document author here>
Abstract: This manual describes what clsync is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/clsync/clsync.sgml.gz

Format: postscript
Files: /usr/share/doc/clsync/clsync.ps.gz

Format: text
Files: /usr/share/doc/clsync/clsync.text.gz

Format: HTML
Index: /usr/share/doc/clsync/html/index.html
Files: /usr/share/doc/clsync/html/*.html
