.\" Sorry for my English 
.\" --Dmitry Yu Okunev <dyokunev@ut.mephi.ru> 0x8E30679C
.\"
.\" Thanks to oldlaptop [https://github.com/oldlaptop] for spell and
.\" grammar correction of this page.
.\"
.TH CLSYNC 1 "JULY 2013" Linux "User Manuals"
.SH NAME
clsync \- live sync tool, written in GNU C
.SH SYNOPSIS
.B clsync [\-bpvDqfih] 
.B [\-t
.I ordinary\-delay
.B ]
.B [\-w
.I additional\-delay
.B ]
.B [\-d
.I tmpdir\-path
.B ]
.B [\-B
.I filesize\-theshold
.B ]
.B [\-t
.I bigfiles\-delay
.B ]
.B [\-l
.I label
.B ]
.I watch\-dir
.I action\-script
.B [
.I rules\-file
.B ]
.B [
.I dest-dir
.B ]
.SH DESCRIPTION
.B clsync
executes
.I action\-script
with appropriate arguments on FS events in directory
.I watch\-dir
using the
.BR inotify (7)
Linux kernel subsystem.

Extended regex\-rules to filter what files and
directories to sync may be placed in
.I rules\-file


.SH OPTIONS

.B \-b, \-\-background
.RS 8
Daemonize, forcing clsync to fork() on start.

.PP
.RE
.B \-p, \-\-pthread
.RS 8
Use
.BR pthreads (7)
to parallelize syncing processes.

If you're running
.B clsync
with option
.B \-\-pthread
in conjunction with
.B rsync
with option
.B \-\-backup
, you may catch a bug due to nonatomicity of rsync's file replace operation.
(see
.B DIAGNOSTICS
)
.RE

.PP
.B \-c, \-\-cluster\-iface
.I interface\-ip
.RS 8
Enables inter-node notifing subsystem to prevent sync looping between nodes.
This's very useful features that provides ability of birectional sync of the
same directory between two or more nodes.
.I interface-ip
is an IP-address already assigned to the interface that will be used for
multicast notifing.

Not enabled by default.

To find out the IP-address on interface "eth0", you can use for example next
command:

ip a s eth0 | awk '{if($1=="inet") {gsub("/.*", "", $2); print $2}}'
.RE

.PP
.B \-c, \-\-cluster\-ip
.I multicast\-ip
.RS 8
Sets IP-address for multicast group.

This option can be used only in conjuction with
.B \-\-cluster\-interface
\*S.

Use IP-addresses from 224.0.0.0/4 for this option.

Default value is "227.108.115.121". [(128+"c")."l"."s"."y"]
.RE

.PP
.B \-c, \-\-cluster\-timeout
.I cluster\-timeout
.RS 8
Sets timeout (in milliseconds) of waiting answer from another nodes of the cluster.
If there's no answer from some node, it will be excluded.

Default value is "1000". [1 second]
.RE

.PP
.B \-t, \-\-collectdelay
.I ordinary\-delay
.RS 8
Sets the delay (in seconds) to collect events about ordinary files and
directories.

Default value is "30".
.RE

.PP
.B \-w, \-\-syncdelay
.I additional\-delay
.RS 8
Sets the minimal delay (in seconds) between syncs.

Default value is "30".
.RE

.PP
.B \-d, \-\-outlistsdir
.I tmpdir\-path
.RS 8
Sets directory path to output temporary events\-lists files.

If this option is enabled,
.B clsync
will execute
.I action\-script
once for each aggregated event list, passing the path to a file containing
this list (action "synclist").
Otherwise,
.B clsync
will execute
.I action\-script
for every file in the aggregated event list (action "sync").

See
.B ACTION SCRIPT
\*S.

Is not set by default.
.RE

.PP
.B \-R, \-\-rsync
.RS 8
Forces
.B clsync
to use "rsynclist" action instead of "initialsync" and "synclist" (see 
.B ACTION SCRIPT
). This option can be used only with
.I \-\-outlistsdir
option.

Recommended option.

You can use "-RR" to run "rsync" directly, bypassing intermediate script
(see
.B ACTION SCRIPT
case
.B e
)

Is not set by default.
.RE

.PP
.B \-L, \-\-rsyncinclimit
.I rsync\-includes\-line\-limit
.RS 8
Sets soft limit for lines count in files by path
.I rsync\-listpath
\*S. Unfortunately, rsync works very slowly with huge "\-\-include\-from"
files. So,
.B clsync
splits that list with approximately
.I rsync\-includes\-line\-limit
lines per list if it's too big, and executes by one rsync instance per list
part. Use value "0" to disable the limit.

Default value is "20000".
.RE

.PP
.B \-I, \-\-rsyncpreferinclude
.RS 8
Forces
.B clsync
to prefer a "lot of includes" method instead of a "excludes+includes" for
rsync on recursive syncing.

See
.B case d
of
.B ACTION SCRIPT
\*S.

This option is not recommended.

Is not set by default.
.RE

.PP
.B \-U, \-\-dontunlinklists
.RS 8
Do not delete list\-files after
.I action\-script
has finished.

This may be used for debugging purposes.

Is not set by default.
.RE

.PP
.B \-F, \-\-fullinitialsync
.RS 8
Ignore filter rules from
.I rules-file
on initial sync.

This may be useful, e.g. if it's required to sync "/var/log/" tree but not
sync every change from there.

Is not set by default.
.RE

.PP
.B \-B, \-\-bigfilethreshold
.I filesize\-threshold
.RS 8
Sets file size threshold (in bytes) that separates ordinary files from
"big files". Events about "big files" are processed in another queue with a
separate collecting delay. This is supposed to be used as a means of unloading
IO resources.

Default value is "134217728" ["128 MiB"].
.RE

.PP
.B \-T, \-\-bigfilescollectdelay
.I bigfiles\-delay
.RS 8
Sets the delay (in seconds) to collect events about "big files" (see
.I filesize\-threshold
).

Default value is "1800".
.RE

.PP
.B \-k, \-\-synctimeout
.I sync-timeout
.RS 8
Sets timeout for syncing processes.
.B clsync
will die if syncing process alive more than
.I sync-timeout
seconds.

Set "0" to disable the timeout.

Default value is "86400" ["24 hours"].
.RE

.PP
.B \-v, \-\-verbose
.RS 8
This option is supposed to increase verbosity. But at the moment there's no
"verbose output" in the code, so the option does nothing. :)
.RE

.PP
.B \-D, \-\-debug
.RS 8
Increases debugging output. This may be supplied multiple times for more
debugging information, up to a maximum of three "D" flags (more will do 
nothing), for example: \-DDD
.RE

.PP
.B \-q, \-\-quite
.RS 8
Suppresses error messages.
.RE

.PP
.B \-f, \-\-fanotify
.RS 8
Switches monitor subsystem to "fanotify" [it's described for
future\-compatibility].
.I Don't_use_this_option!
.RE

.PP
.B \-i, \-\-inotify
.RS 8
Switches monitor subsystem to "inotify".

Is set by default.
.RE

.PP
.B \-l, \-\-label
.I label
.RS 8
Sets a label for this instance of clsync. The
.I label
will be passed to
.I action\-script
every execution.

Default value is "nolabel".
.RE

.PP
.B \-h, \-\-help
.RS 8
Outputs options list and exits with exitcode "0".
.RE

.PP
.B \-V, \-\-version
.RS 8
Outputs clsync version and exits with exitcode "0".
.RE

.SH ACTION SCRIPT
.B clsync
executes
.I action\-script
that supposed to take care of the actual syncing process. Therefore
.B clsync
is only a convenient way to run a syncing script.

.B clsync
can run
.I action\-script
in five ways:

case
.B a
.RS
.I action\-script
initialsync
.I label dirpath

In this case,
.I action\-script
is supposed to recursively sync data from directory by path
.I dirpath
with manual excluding extra files.
.RE

case
.B b
.RS
.I action\-script
sync
.I label evmask path

In this case,
.I action\-script
is supposed to non\-recursively sync file or directory by
.I path
\*S. With
.I evmask
it's passed bitmask of events with the file or directory (see 
"/usr/include/linux/inotify.h").
.RE

case
.B c
.RS
.I action\-script
synclist
.I label listpath

In this case,
.I action\-script
is supposed to non\-recursively sync files and directories from list in a file by
path
.I listpath
\*S(see below). With
.I evmask
it's passed bitmask of events with the file or directory (see 
"/usr/include/linux/inotify.h").
.RE

case
.B d
.RS
.I action\-script
rsynclist
.I label rsync\-listpath [rsync\-exclude\-listpath]

In this case,
.I action\-script
is supposed to run "rsync" application with parameters: 

\-aH \-\-delete\-before \-\-include\-from
.I rsync\-listpath
\-\-exclude '*'

if option
.I \-\-rsyncpreferinclude
is enabled.

And with parameters:

\-aH \-\-delete\-before \-\-exclude\-from
.I rsync\-exclude\-listpath
\-\-include\-from
.I rsync\-listpath
\-\-exclude '*'

if option
.I \-\-rsyncpreferinclude
is disabled.
.RE

case
.B e
.RS
.I action\-script
\-\-inplace \-avH \-\-delete\-before [\-\-exclude\-from
.I rsync\-exclude\-listpath
]
\-\-include\-from
.I rsync\-listpath
\-\-exclude '*'
.I watch-dir/ dest-dir/

In this case,
.I action\-script
is supposed to be a path to
.B rsync
binary.

Error code "24" from
.I action-script
will be ignored in this case.
.RE

As can be noticed, in the first four cases clsync's
.I label
is passed (see 
.I \-\-label
).

The listfile by path
.I listpath
contains lines separated by NL (without CR) of next format:
.RS
sync
.I label evmask path

Every lines is supposed to be proceed by external syncer to sync file or
directory by path
.I path
\*S. With
.I evmask
it's passed bitmask of events with the file or directory (see
"/usr/include/linux/inotify.h").

.RE

.SH RULES
Filter riles can be placed into
.I rules\-file
with one rule per line.

Rule format:
.I [+\-][fd*]regexp

.I +
\- means include;
.I \-
\- means exclude;
.I f
\- means file;
.I d
\- means directory;
.I *
\- means all.

For example: \-*/[Tt]estdir

.SH SIGNALS
1  \- to reread filter rules

10 \- runs threads' GC function

12 \- runs full resync


.SH DIAGNOSTICS

initial rsync process works very slow on clsync start
.RS
Probably there's too huge exclude list is passed to rsync. This can happened
if you're excluding with regex in clsync's rules a lot of thousands files.
They will be passed to rsync's exclude list one by one.

To diagnose it, you can use "-U" option and look into 
.I rsync\-exclude\-listpath
file (see
.B ACTION SCRIPT
case 
.B d
)

To prevent this, it's recommended to write such rules for rsync directly 
(not via clsync).

For example, often problem is with PHP's session files. You shouldn't exclude
them in clsync's rules with "-f/sess_.*", but you should exclude it in rsync
directly (e.g with «--exclude "sess_*"»).
.RE

The following diagnostics may be issued on stderr:

Error: Cannot inotify_add_watch() on [...]
.RS
Not enough inotify watching descriptors is allowed. It can be fixed
by increasing value of "sysctl fs.inotify.max_user_watches"
.RE

Error: Got non-zero exitcode
.I exitcode
[...]
.RS
.I action-script
returned non-zero exitcode. Probably, you should process exitcodes in it or
your syncer process didn't worked well. I case of using rsync, you can find
the exitcodes meanings in
.B man 1 rsync
\*S.

If
.I exitcode
equals to 23 and you're using
.B clsync
in conjunction with
.B rsync
, this may happend, for example in next cases:

.RS

\- Not enough space on destination.

\- You're running clsync with 
.B \-\-pthread
and rsync with
.B \-\-backup
\*S. See bugreport by URL:
.I https://bugzilla.samba.org/show_bug.cgi?id=10081
\*S.

.RE

To confirm the problem, you can try to add "return 0" or "exit 0" into
your
.I action-script
\*S.

.RE

.SH EXAMPLES
Working example you can try out in "example/" or 
"/usr/share/doc/clsync/example/" directory. Copy this directory somewhere
(e.g. into "/tmp"). And try to run "clsync-start.sh" in there. Any
files/directories modifications in "example/testdir/from" will be synced to
"example/testdir/to" with few seconds delay.
.RE
.SH AUTHOR
Dmitry Yu Okunev <xai@mephi.ru> 0x8E30679C
.SH "SEE ALSO"
.BR rsync (1),
.BR pthreads (7),
.BR inotify (7)

